/*! This file was generated by vite-i18n-gen-resources-type check https://github.com/CRMChatReactComponent/vite-i18n-gen-resources-type. Please do not modify. */
export interface I18nResourceInterface {
  common: {
    confirmDelete: "确定删除吗？";
    noData: "没有数据";
    selectAGroupFirst: "请在左侧选择一个分组";
    addNewGroup: "添加一个分组";
    editGroup: "编辑分组";
    createGroup: "新建分组";
    titleFieldName: "标题";
    colorFieldName: "颜色";
    save: "保存";
    create: "创建";
    quickMessageConfigs: "快捷消息配置";
    createSuccessfully: "创建成功";
    cannotSavedMessageCuzLabelExisted: "无法保存: 标题重复";
    cannotSavedMessageCuzLabelEmpty: "无法保存: 标题不能为空";
    cannotSavedMessageCuzContentEmpty: "无法保存: 内容不能为空";
    content: "内容";
    delete: "删除";
    importFromClipboard: "从剪切板导入";
  };
}
